name: videosdk_flutter_example
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  videosdk: ^1.2.1
  http: ^1.1.0
  flutter_dotenv: ^5.0.2
  flutter_svg: ^2.0.2
  date_time_format: ^2.0.1
  touch_ripple_effect: ^2.2.3
  lottie: ^2.2.0
  responsive_framework: 1.1.1
  window_manager: ^0.3.4
  cupertino_icons: ^1.0.6
  google_fonts: ^5.1.0

  # State Management
  provider: ^6.0.5

  # Calendar and Date
  table_calendar: ^3.1.2
  intl: ^0.19.0

  url_launcher: ^6.0.12

  # Firebase
  cloud_firestore: ^5.6.0
  firebase_messaging: ^15.1.6
  path_provider: ^2.0.15
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  firebase_storage: ^12.2.0
  firebase_database: ^11.1.0
  file_picker: ^8.1.7 # Replace with the latest version
  just_audio: ^0.9.42




dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env
