// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-f1afwFMg-0aafrtI1-w6CaoFkwC2fTw',
    appId: '1:535015116281:web:bf1054bc04201cfbe88128',
    messagingSenderId: '535015116281',
    projectId: 'zresume-67ec9',
    authDomain: 'zresume-67ec9.firebaseapp.com',
    databaseURL: 'https://zresume-67ec9-default-rtdb.firebaseio.com',
    storageBucket: 'zresume-67ec9.appspot.com',
    measurementId: 'G-66KJ3N85QH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-tGZOK6SVm9EWEqqbova6KvMwPCvPmh8',
    appId: '1:535015116281:android:0afd6f9a123eddbce88128',
    messagingSenderId: '535015116281',
    projectId: 'zresume-67ec9',
    databaseURL: 'https://zresume-67ec9-default-rtdb.firebaseio.com',
    storageBucket: 'zresume-67ec9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyBBu5HDN6cGPP5ZmF8ufej6nU4nn4NAE',
    appId: '1:535015116281:ios:f2ad741c017fbbdbe88128',
    messagingSenderId: '535015116281',
    projectId: 'zresume-67ec9',
    databaseURL: 'https://zresume-67ec9-default-rtdb.firebaseio.com',
    storageBucket: 'zresume-67ec9.appspot.com',
    androidClientId: '535015116281-f8qkrpp4ngeemn4mps3rjnvjmct8had4.apps.googleusercontent.com',
    iosClientId: '535015116281-gqhujleg7amfgva0aac9arr0k6fuhcle.apps.googleusercontent.com',
    iosBundleId: 'com.example.videosdkFlutterExample',
  );

}